title: My Own Private Idaho
logo: /assets/img/logo.png
description: A place for writing, art, and other multimedia. Maxwell Kline lives here. The rent is a little under 6 bucks a year.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
